version: 2.1

jobs:
  say-hello:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World! ; cat /etc/os-release ; date"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
